"""empty message

Revision ID: 0d0896457d0b
Revises: ea80a2ed37e4
Create Date: 2026-03-19 21:38:45.282762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0896457d0b'
down_revision = 'ea80a2ed37e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
