"""empty message

Revision ID: 3cd25438bea2
Revises: 27c927a81159
Create Date: 2026-04-07 19:18:25.390897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd25438bea2'
down_revision = '27c927a81159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id_professor', sa.Integer(), nullable=True),
    sa.Column('id_turma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materias')
    # ### end Alembic commands ###
