"""empty message

Revision ID: 4935868f270d
Revises: d416c3d96fc2
Create Date: 2026-03-31 20:17:14.127420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4935868f270d'
down_revision = 'd416c3d96fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('CARTEIRA_ESCOLAR', 'ATESTADO_MATRICULA', 'BOLETIM', 'DCLR_TRANSF', 'HIST_ESCOLAR', 'GRADE_ESCOLAR', name='tipodocumento'), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANALISE', 'PRONTO', 'ENTREGUE', name='statusdocumento'), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    # ### end Alembic commands ###
