"""empty message

Revision ID: 4d0df086032f
Revises: 76879ef3293f
Create Date: 2026-03-02 23:41:39.306175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0df086032f'
down_revision = '76879ef3293f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_professor_user_id', ['user_id'])
        batch_op.create_unique_constraint('uq_professor_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_constraint('uq_professor_user_id', type_='unique')
        batch_op.drop_constraint('uq_professor_user_id', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
