"""empty message

Revision ID: 62f542485e31
Revises: 3cd25438bea2
Create Date: 2026-04-09 20:37:55.186864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f542485e31'
down_revision = '3cd25438bea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('GERAL', 'COMPORTAMENTO', 'SAUDE', 'ADMINISTRATIVO', name='tipoavisoenum'), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('remetente_tipo', sa.String(length=20), nullable=True),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='nivelprioridadeaviso'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aviso_destinatario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aviso_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_tipo', sa.String(length=20), nullable=True),
    sa.Column('lido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aviso_id'], ['aviso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aviso_destinatario')
    op.drop_table('aviso')
    # ### end Alembic commands ###
