"""empty message

Revision ID: 71fc551b9cd0
Revises: 8d15db05c7c6
Create Date: 2026-03-19 20:54:34.855725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fc551b9cd0'
down_revision = '8d15db05c7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro_id', sa.Integer(), nullable=True))
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_foreign_key('fk_responsavel_logradouro', 'logradouros', ['logradouro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_responsavel_logradouro', type_='foreignkey')
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('logradouro_id')

    # ### end Alembic commands ###
