"""empty message

Revision ID: 7b8d05a1f47b
Revises: a4c2443ea646
Create Date: 2026-03-19 20:34:12.589806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8d05a1f47b'
down_revision = 'a4c2443ea646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro_id', sa.Integer(), nullable=True))
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key('fk_aluno_logradouro', 'logradouros', ['logradouro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint('fk_aluno_logradouro', type_='foreignkey')
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('logradouro_id')

    # ### end Alembic commands ###
