"""empty message

Revision ID: 8d15db05c7c6
Revises: 7b8d05a1f47b
Create Date: 2026-03-19 20:34:53.148501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d15db05c7c6'
down_revision = '7b8d05a1f47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
