"""empty message

Revision ID: 9cf38f26bf29
Revises: 71fc551b9cd0
Create Date: 2026-03-19 20:55:23.481857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf38f26bf29'
down_revision = '71fc551b9cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
