"""empty message

Revision ID: dc50db824b82
Revises: fd2a4009a0fc
Create Date: 2026-03-19 20:02:41.986477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc50db824b82'
down_revision = 'fd2a4009a0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricula', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_matricula', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo_sanguineo', sa.String(length=3), nullable=True))
        batch_op.create_unique_constraint('uq_aluno_matricula', ['matricula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint('uq_aluno_matricula', type_='unique')
        batch_op.drop_column('tipo_sanguineo')
        batch_op.drop_column('data_matricula')
        batch_op.drop_column('matricula')

    # ### end Alembic commands ###
