"""empty message

Revision ID: ea80a2ed37e4
Revises: 3266526308d1
Create Date: 2026-03-19 21:38:31.367941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea80a2ed37e4'
down_revision = '3266526308d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro_id', sa.Integer(), nullable=True))
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key('fk_professor_logradouro', 'logradouros', ['logradouro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_professor_logradouro', type_='foreignkey')
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('logradouro_id')

    # ### end Alembic commands ###
