"""empty message

Revision ID: eed4f08a3ca7
Revises: d773fb9c8194
Create Date: 2026-03-03 00:07:54.773169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed4f08a3ca7'
down_revision = 'd773fb9c8194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('responsavel_aluno',
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('responsavel_id', 'aluno_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsavel_aluno')
    op.drop_table('responsavel')
    # ### end Alembic commands ###
