"""empty message

Revision ID: fd2a4009a0fc
Revises: eed4f08a3ca7
Create Date: 2026-03-13 21:46:25.972672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2a4009a0fc'
down_revision = 'eed4f08a3ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_aluno_turma', 'turmas', ['turma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint('fk_aluno_turma', type_='foreignkey')
        batch_op.drop_column('turma_id')

    # ### end Alembic commands ###
